# Site settings
author: Patrick Harrison
title: 
header-img: img/home-bg.png
email: jahman@bellatlantic.net
copyright_name: Patrick Harrison
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jahman07104

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
